apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]